### ISSUE TITLE
Add Redis functions ZCARD, ZREMRANGEBYSCORE, ZRANGE, ZADD, ZREM

### ISSUE THREAD

**Issue by rfdickerson** [Kitura/Kitura-redis#11]
Some of our work for creating a Redis-based TodoList requires set-based operations. I was wondering if the API in fact has these but we missed them, or maybe we can get these functions added, or if we can file a PR to add them. @chiahuang

**Comment by rfdickerson** [comment]
@chiahuang has implemented the above functions. We are just going to finish writing the unit tests and file a PR.

**Comment by shmuelk** [comment]
@rfdickerson and @chiahuang Thank you very much for helping to complete our Redis API coverage.

BTW Did you add the "transactional" equivalents if applicable?

**Comment by dfirsht** [comment]
Completed in PR: https://github.com/IBM-Swift/Kitura-redis/pull/12
