### ISSUE TITLE
test_expiration test case failing

### ISSUE THREAD

**Issue by kweinmeister** [Kitura/Kitura-redis#5]
Test Case '-[SwiftRedisTestSuite.TestMoreCommands test_expiration]' started.
/Users/travis/build/IBM-Swift/Kitura-redis/Tests/SwiftRedis/TestMoreCommands.swift:170: error: -[SwiftRedisTestSuite.TestMoreCommands test_expiration] : XCTAssertEqual failed: ("Optional(1.849)") is not equal to ("Optional(1.8500000000000001)") - ttl for test1 should be 1.85. It was 1.849
Test Case '-[SwiftRedisTestSuite.TestMoreCommands test_expiration]' failed (0.007 seconds).

**Comment by kweinmeister** [comment]
Passes in most recent Travis builds. Closing.

**Comment by shmuelk** [comment]
These tests sometimes pass sometimes fail.

**Comment by irar2** [comment]
Reviewed code and build passes
