### ISSUE TITLE
Kitura-redis and Kitura-Session-Redis tests failing

### ISSUE THREAD

**Issue by djones6** [Kitura/Kitura-redis#70]
IBM-Swift/Kitura-redis#69 and IBM-Swift/Kitura-Session-Redis#41 are failing most Linux builds.

I do not believe the cause of the failure is the (relatively benign) changes in the PRs themselves, so something else has happened.  I suspect a change to the environment / version of Redis that gets installed, or similar.

The builds don't produce anything that obviously stands out as a problem, but the tests fail to connect to the local Redis instance.

**Comment by Andrew-Lees11** [comment]
The tests started passing again without any changes. We assume something was changed in redis which was then patched. The only build that is currently failing is Ubuntu 18.04.

**Comment by Andrew-Lees11** [comment]
Closing since all the tests started passing without any changes. Issue was probably with redis on linux instead of our repo.
